### ISSUE TITLE
Can you get the result in CIFAR10 of the paper?

### ISSUE THREAD

**Issue by leondada** [AshwinRJ/Federated-Learning-PyTorch#2]
The result of paper is so good ,but i can't get similar result by this code

**Comment by AshwinRJ** [comment]
The CNN arch for CIFAR used in this repo does have 2 Conv layers followed by 3 linear layers. Maybe you aren't getting the same result as the paper maybe because they used different hidden size for these layers in their implementation. The paper describes the architecture they used for CIFAR in the following way: 

>The model the architecture was taken from the TensorFlow tutorial [https://www.tensorflow.org/tutorials], which consists of two convolutional layers followed by two fully-connected layers and then a linear transformation layer.
